services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:${HTTP_PORT}"

  postgres:
    container_name: cart_postgres
    image: postgres:17
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data

volumes:
  cart_postgres_data: