// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cart

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	UserID    int64
	SkuID     int64
	Count     int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
