// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cart

import (
	"context"
)

const deleteCartItems = `-- name: DeleteCartItems :exec
DELETE
FROM cart_items
WHERE user_id = $1
`

func (q *Queries) DeleteCartItems(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCartItems, userID)
	return err
}

const ensureCart = `-- name: EnsureCart :exec
INSERT INTO carts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, ensureCart, userID)
	return err
}

const getCart = `-- name: GetCart :one
SELECT user_id
FROM carts
WHERE user_id = $1
`

func (q *Queries) GetCart(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getCart, userID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT sku_id, count
FROM cart_items
WHERE user_id = $1
`

type GetCartItemsRow struct {
	SkuID int64
	Count int16
}

func (q *Queries) GetCartItems(ctx context.Context, userID int64) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(&i.SkuID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (user_id, sku_id, count)
VALUES ($1, $2, $3)
`

type InsertCartItemParams struct {
	UserID int64
	SkuID  int64
	Count  int16
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.Exec(ctx, insertCartItem, arg.UserID, arg.SkuID, arg.Count)
	return err
}
