// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shizakira/cart/internal/domain"
	"github.com/shizakira/cart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type Storage
func (_mock *Storage) Clear(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Storage_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Storage_Expecter) Clear(ctx interface{}, userID interface{}) *Storage_Clear_Call {
	return &Storage_Clear_Call{Call: _e.mock.On("Clear", ctx, userID)}
}

func (_c *Storage_Clear_Call) Run(run func(ctx context.Context, userID int)) *Storage_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_Clear_Call) Return(err error) *Storage_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Clear_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *Storage_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type Storage
func (_mock *Storage) Find(ctx context.Context, userID int) (*domain.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Storage_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Storage_Expecter) Find(ctx interface{}, userID interface{}) *Storage_Find_Call {
	return &Storage_Find_Call{Call: _e.mock.On("Find", ctx, userID)}
}

func (_c *Storage_Find_Call) Run(run func(ctx context.Context, userID int)) *Storage_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_Find_Call) Return(cart *domain.Cart, err error) *Storage_Find_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *Storage_Find_Call) RunAndReturn(run func(ctx context.Context, userID int) (*domain.Cart, error)) *Storage_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Storage
func (_mock *Storage) Save(ctx context.Context, cart *domain.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Storage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - cart
func (_e *Storage_Expecter) Save(ctx interface{}, cart interface{}) *Storage_Save_Call {
	return &Storage_Save_Call{Call: _e.mock.On("Save", ctx, cart)}
}

func (_c *Storage_Save_Call) Run(run func(ctx context.Context, cart *domain.Cart)) *Storage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Cart))
	})
	return _c
}

func (_c *Storage_Save_Call) Return(err error) *Storage_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_Save_Call) RunAndReturn(run func(ctx context.Context, cart *domain.Cart) error) *Storage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function for the type ProductService
func (_mock *ProductService) GetProduct(ctx context.Context, skuID int) (model.Product, error) {
	ret := _mock.Called(ctx, skuID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Product, error)); ok {
		return returnFunc(ctx, skuID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Product); ok {
		r0 = returnFunc(ctx, skuID)
	} else {
		r0 = ret.Get(0).(model.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, skuID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type ProductService_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx
//   - skuID
func (_e *ProductService_Expecter) GetProduct(ctx interface{}, skuID interface{}) *ProductService_GetProduct_Call {
	return &ProductService_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, skuID)}
}

func (_c *ProductService_GetProduct_Call) Run(run func(ctx context.Context, skuID int)) *ProductService_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ProductService_GetProduct_Call) Return(product model.Product, err error) *ProductService_GetProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_GetProduct_Call) RunAndReturn(run func(ctx context.Context, skuID int) (model.Product, error)) *ProductService_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}
