// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shizakira/cart/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type Storage
func (_mock *Storage) AddItem(ctx context.Context, userID int, skuID int, count uint) error {
	ret := _mock.Called(ctx, userID, skuID, count)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, uint) error); ok {
		r0 = returnFunc(ctx, userID, skuID, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type Storage_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx
//   - userID
//   - skuID
//   - count
func (_e *Storage_Expecter) AddItem(ctx interface{}, userID interface{}, skuID interface{}, count interface{}) *Storage_AddItem_Call {
	return &Storage_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, skuID, count)}
}

func (_c *Storage_AddItem_Call) Run(run func(ctx context.Context, userID int, skuID int, count uint)) *Storage_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(uint))
	})
	return _c
}

func (_c *Storage_AddItem_Call) Return(err error) *Storage_AddItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_AddItem_Call) RunAndReturn(run func(ctx context.Context, userID int, skuID int, count uint) error) *Storage_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// ClearByUserID provides a mock function for the type Storage
func (_mock *Storage) ClearByUserID(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_ClearByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearByUserID'
type Storage_ClearByUserID_Call struct {
	*mock.Call
}

// ClearByUserID is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Storage_Expecter) ClearByUserID(ctx interface{}, userID interface{}) *Storage_ClearByUserID_Call {
	return &Storage_ClearByUserID_Call{Call: _e.mock.On("ClearByUserID", ctx, userID)}
}

func (_c *Storage_ClearByUserID_Call) Run(run func(ctx context.Context, userID int)) *Storage_ClearByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_ClearByUserID_Call) Return(err error) *Storage_ClearByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_ClearByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *Storage_ClearByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type Storage
func (_mock *Storage) FindByUserID(ctx context.Context, userID int) (domain.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type Storage_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Storage_Expecter) FindByUserID(ctx interface{}, userID interface{}) *Storage_FindByUserID_Call {
	return &Storage_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *Storage_FindByUserID_Call) Run(run func(ctx context.Context, userID int)) *Storage_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_FindByUserID_Call) Return(cart domain.Cart, err error) *Storage_FindByUserID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *Storage_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) (domain.Cart, error)) *Storage_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function for the type Storage
func (_mock *Storage) RemoveItem(ctx context.Context, userID int, skuID int) error {
	ret := _mock.Called(ctx, userID, skuID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userID, skuID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type Storage_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx
//   - userID
//   - skuID
func (_e *Storage_Expecter) RemoveItem(ctx interface{}, userID interface{}, skuID interface{}) *Storage_RemoveItem_Call {
	return &Storage_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, userID, skuID)}
}

func (_c *Storage_RemoveItem_Call) Run(run func(ctx context.Context, userID int, skuID int)) *Storage_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *Storage_RemoveItem_Call) Return(err error) *Storage_RemoveItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_RemoveItem_Call) RunAndReturn(run func(ctx context.Context, userID int, skuID int) error) *Storage_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// IsProductExist provides a mock function for the type ProductService
func (_mock *ProductService) IsProductExist(ctx context.Context, sku int) (bool, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for IsProductExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_IsProductExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProductExist'
type ProductService_IsProductExist_Call struct {
	*mock.Call
}

// IsProductExist is a helper method to define mock.On call
//   - ctx
//   - sku
func (_e *ProductService_Expecter) IsProductExist(ctx interface{}, sku interface{}) *ProductService_IsProductExist_Call {
	return &ProductService_IsProductExist_Call{Call: _e.mock.On("IsProductExist", ctx, sku)}
}

func (_c *ProductService_IsProductExist_Call) Run(run func(ctx context.Context, sku int)) *ProductService_IsProductExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ProductService_IsProductExist_Call) Return(b bool, err error) *ProductService_IsProductExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ProductService_IsProductExist_Call) RunAndReturn(run func(ctx context.Context, sku int) (bool, error)) *ProductService_IsProductExist_Call {
	_c.Call.Return(run)
	return _c
}
